### ISSUE TITLE
Enable remote debugging

### ISSUE THREAD

**Issue by rauljmz** [adminb-solutions/SampleSitecoreSolution#1]
This probably requires modifying the base image

**Comment by kevinobee** [comment]
@rauljmz The change has been migrated to an [Issue 6](https://github.com/adminb-solutions/sitecore-docker/issues/6) issue in the [adminb-solutions/sitecore-docker](https://github.com/adminb-solutions/sitecore-docker) repository.

A PR has been created to fix this issue. See [Add Remote Debugger support to Sitecore Docker images #7](https://github.com/adminb-solutions/sitecore-docker/pull/7) for details.
